### ISSUE TITLE
Describir proceso de creación de trabajos en equipo

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/punto_inicio#2]
Ahora en moodle tenemos (por ejemplo, para el E105):

**Todos los integrantes del equipo deben realizar al menos los pasos 1, 2 y 3 para que los grupos queden correctamente definidos en GitHub.**

- Accede a este enlace: https://classroom.github.com/g/w23oz_ie
- Elige el nombre de tu equipo. Si aún no existe, crea un nuevo nombre y avisa a tus compañeros de equipo para que elijan el mismo.
- Una vez aceptada la tarea (assignment), se creará un repositorio nuevo en AIGORA, con la ruta https://github.com/aigora/twE105-[nombre-equipo], siendo [nombre-equipo] el identificador que hayas elegido en el punto 2.
- Clonad este repositorio remoto a una copia local.
- Este repositorio está inicializado con un .gitignore, una licencia, y una plantilla README.md. Debéis modificar este README.md cumplimentando la información que ahí se indica. No olvidéis emplear la [sintaxis de Markdown](https://guides.github.com/features/mastering-markdown/#syntax) para el formato de este fichero.
- Cuando hayáis completado el README.md, confirmad los cambios (COMMIT) y sincronizad la copia local con el repositorio remoto (PULL y después PUSH). Si aún tenéis dificultades usando GitHub Desktop, podéis modificar el README.md directamente en la web, pulsando el lápiz para editar.

**Comment by Juliauru** [comment]
He hecho una primera versión, en base a lo que pusiste en el mensaje.  Espero que esté correcto. 
[Cómo comenzar con el trabajo en grupo en GitHub](https://github.com/aigora/punto_inicio/wiki/C%C3%B3mo-comenzar-con-el-trabajo-en-grupo-en-GitHub)
