### ISSUE TITLE
Añadir instrucciones para formar el equipo

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/punto_inicio#5]
Por favor, dadle prioridad a esto ya que los alumnos están un poco perdidos.
Si lo hacéis en una página en el Wiki, en cuanto esté les puedo pasar el enlace.

**Comment by oscarperpinan** [comment]
¿Que diferencia hay con la issue #2?

**Comment by raquelcedazo** [comment]
Cierto, no la ví 👍
